[package]
name = "fpm"
version = "0.1.0"
edition = "2021"
authors = ["Luke Eltiste"]
description = "A CLI Program to help manage projects"
readme = "README.md"
repository = "https://github.com/Frazzer951/fpm"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
dirs = "4.0.0"
itertools = "0.10.3"
regex = "1.5.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.137"
serde_json = "1.0.79"
serde_yaml = "0.8.24"
toml = "0.5.9"