[package]
name = "fpm"
version = "0.2.0"
edition = "2021"
authors = ["Luke Eltiste"]
description = "A CLI Program to help manage projects"
readme = "README.md"
repository = "https://github.com/Frazzer951/fpm"

[dependencies]
clap = { version = "3.2", features = ["derive", "cargo"] }
config = "0.13"
dirs = "4.0"
itertools = "0.10"
opener = "0.5"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
strsim = "0.10"
toml = "0.5"