edition = "2021"
match_block_trailing_comma = true
max_width = 127
merge_derives = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
