[package]
edition = "2021"
name = "fpm"
version = "0.1.0"

[dependencies]
clap = {version = "4.0", features = ["cargo"]}
console = "0.15"
dialoguer = "0.10"
eyre = "0.6"
indicatif = "0.17"
lib_fpm = {path = "../lib_fpm"}
thiserror = "1.0"
