[package]
edition = "2021"
name = "fpm-cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fpm-cli"
path = "./src/main.rs"

[[bin]]
name = "fpm"
path = "./src/main.rs"

[dependencies]
fpm = {path = "../fpm"}
