name: Generate changelog
on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit new CHANGELOG
        run: |
          git config --global user.name 'Frazzer951'
          git config --global user.email 'luke343279@gmail.com'
          [[ -n $(git status -s) ]] && git commit -am "docs: update CHANGELOG"
          git push origin main
