name: Format and Clippy Fixes

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    name: Format and Clippy Fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: "rustfmt, clippy"

      - uses: Swatinem/rust-cache@v1.4.0
        with:
          sharedKey: cache

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--verbose"

      - name: Clippy with warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "--fix --allow-dirty"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Cargo Fmt and Clippy Fixes"
          title: "Cargo Fmt and Clippy Fixes"
          delete-branch: true