name: Release

on:
  push:
    tags:
      - "*"

env:
  toolchain_version: stable

jobs:
  release-matrix:
    strategy:
      matrix:
        config:
          - { name: linux, os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { name: windows, os: windows-latest, target: x86_64-pc-windows-msvc }
          - { name: macos, os: macOS-latest, target: x86_64-apple-darwin }
        binary: [fpm, fpm-cli]
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: get_version
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain_version }}
          target: ${{ matrix.config.target }}
          override: true
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.config.target }}
      - name: Prepare package
        run: |
          mkdir binaries
          cp target/${{ matrix.config.target }}/release/${{ matrix.binary }} binaries/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/${{ matrix.binary }}
          asset_name: ${{ matrix.binary }}-${{ matrix.os.name }}-${{ steps.get_version.outputs.tag }}
          tag: ${{ github.ref }}
          overwrite: true
